# Generated by Django 4.0.3 on 2022-04-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_tracker_api', '0002_party_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='master',
        ),
    ]
