# Generated by Django 4.0.3 on 2022-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_tracker_api', '0002_party_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='anon_copper',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='anon_silver',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='anon_gold',
            field=models.BigIntegerField(default=0),
        ),
    ]
