# Generated by Django 4.0.3 on 2022-05-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_tracker_api', '0005_log_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='name',
            field=models.CharField(max_length=69, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='value',
            field=models.BigIntegerField(default=0),
        ),
    ]
