# Generated by Django 4.0.3 on 2022-05-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_tracker_api', '0006_log_name_log_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='value',
            new_name='copper',
        ),
        migrations.AddField(
            model_name='character',
            name='tribute_copper',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='tribute_gold',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='tribute_silver',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='gold',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='silver',
            field=models.BigIntegerField(default=0),
        ),
    ]
