# Generated by Django 3.2.13 on 2022-05-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_tracker_api', '0007_rename_value_log_copper_character_tribute_copper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='time_created',
        ),
    ]
