# Generated by Django 3.2.13 on 2022-10-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_tracker_api', '0008_remove_log_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='master',
            new_name='user_id',
        ),
    ]
